# jekyll build --config _config_live.yml -d "C:\Users\tony\odrive\WebDAV\H Drive\public_html\BNA_NEW"


# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# to generate static site
# 

# copy to public_html

title: "Bath Numerical Analysis"
email: bath-na@lists.bath.ac.uk
author: Bath Numerical Analysis
description: "The home page of the research group in numerical analysis at the University of Bath."
# # the subpath of your site, e.g. /blog
url: "http://people.bath.ac.uk"
baseurl: /tjs42/BNA_NEW
 # the base hostname & protocol for your site, e.g. http://example.com
# logo: "/assets/pics/uob-logo-blue-thumb.gif
# "
markdown: kramdown


# Build settings
permalink: /categories/:year/:title_:month_:day.html
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air"
# "default"  "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
#
collections_dir: my_collections
collections:
    members:
     output: false
    research:
      output: true
      permalink: /research/:name.html
    teaching:
      output: true
#
markdown: kramdown    
#
defaults:
  - scope:
      path: ""
      type: "research"
    values:
      layout: "research_topic"
      sidebar:
        nav: "research"
  - scope:
      path: ""
      type: "teaching"
    values:
      layout: "unit"
      sidebar:
        nav: "teaching"
  - scope:
      path: ""
      type: posts
    values:
      future: true
      layout: single
      classes: wide
      toc: false
      sidebar: 
        nav: "events"
      author_profile: false
      read_time: false
      comments: false

  